################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/olive/OneDrive/Documents/CubeMXPack/stm32wb-matter-device-over-thread-main/Drivers/Sensiron_SCD30_Driver/scd30_i2c.c \
C:/Users/olive/OneDrive/Documents/CubeMXPack/stm32wb-matter-device-over-thread-main/Drivers/Sensiron_SCD30_Driver/sensirion_common.c \
C:/Users/olive/OneDrive/Documents/CubeMXPack/stm32wb-matter-device-over-thread-main/Drivers/Sensiron_SCD30_Driver/sensirion_i2c.c \
C:/Users/olive/OneDrive/Documents/CubeMXPack/stm32wb-matter-device-over-thread-main/Drivers/Sensiron_SCD30_Driver/sensirion_i2c_hal.c 

C_DEPS += \
./Drivers/Sensiron_SCD30_Driver/scd30_i2c.d \
./Drivers/Sensiron_SCD30_Driver/sensirion_common.d \
./Drivers/Sensiron_SCD30_Driver/sensirion_i2c.d \
./Drivers/Sensiron_SCD30_Driver/sensirion_i2c_hal.d 

OBJS += \
./Drivers/Sensiron_SCD30_Driver/scd30_i2c.o \
./Drivers/Sensiron_SCD30_Driver/sensirion_common.o \
./Drivers/Sensiron_SCD30_Driver/sensirion_i2c.o \
./Drivers/Sensiron_SCD30_Driver/sensirion_i2c_hal.o 


# Each subdirectory must supply rules for building sources it contributes
Drivers/Sensiron_SCD30_Driver/scd30_i2c.o: C:/Users/olive/OneDrive/Documents/CubeMXPack/stm32wb-matter-device-over-thread-main/Drivers/Sensiron_SCD30_Driver/scd30_i2c.c Drivers/Sensiron_SCD30_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 '-DCHIP_PLATFORM_CONFIG_INCLUDE=<CHIPPlatformConfig.h>' '-DCHIP_PROJECT_CONFIG_INCLUDE=<CHIPProjectConfig.h>' '-DMBEDTLS_CONFIG_FILE=<matter_config.h>' -DCHIP_HAVE_CONFIG_H -DUSE_HAL_DRIVER '-DOPENTHREAD_CONFIG_FILE=<openthread_api_config_matter.h>' -DCORE_CM4 -DTHREAD_WB -DDEBUG -DSTM32WB55xx -DUSE_STM32WBXX_NUCLEO -c -I../../Core/Inc -I../../Codegen/ -I../../STM32_WPAN/App -I../../STM32_WPAN/Target -I../../../../../../../Utilities/lpm/tiny_lpm -I../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../../../../../Middlewares/ST/STM32_WPAN -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/auto -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/template -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Inc -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Src -I../../../../../../../Middlewares/ST/STM32_WPAN/ble -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/include/openthread -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/src/core -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/src/core/config -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/include -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/core/openthread_api -I../../../../../../../Middlewares/ST/STM32_WPAN/utilities -I../../../../../../../Drivers/BSP/P-NUCLEO-WB55.Nucleo -I../../../../../../../Drivers/BSP/Components/s25fl128s -I../../../../../../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc/Legacy -I../../../../../../../Middlewares/Third_Party/mbedTLS/library -I../../../../../../../Middlewares/Third_Party/mbedTLS/include -I../../../../../../../Middlewares/Third_Party/connectedhomeip/src/platform/stm32 -I../../../../../../../Middlewares/Third_Party/connectedhomeip/src/platform -Os -ffunction-sections -fdata-sections -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/Sensiron_SCD30_Driver/sensirion_common.o: C:/Users/olive/OneDrive/Documents/CubeMXPack/stm32wb-matter-device-over-thread-main/Drivers/Sensiron_SCD30_Driver/sensirion_common.c Drivers/Sensiron_SCD30_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 '-DCHIP_PLATFORM_CONFIG_INCLUDE=<CHIPPlatformConfig.h>' '-DCHIP_PROJECT_CONFIG_INCLUDE=<CHIPProjectConfig.h>' '-DMBEDTLS_CONFIG_FILE=<matter_config.h>' -DCHIP_HAVE_CONFIG_H -DUSE_HAL_DRIVER '-DOPENTHREAD_CONFIG_FILE=<openthread_api_config_matter.h>' -DCORE_CM4 -DTHREAD_WB -DDEBUG -DSTM32WB55xx -DUSE_STM32WBXX_NUCLEO -c -I../../Core/Inc -I../../Codegen/ -I../../STM32_WPAN/App -I../../STM32_WPAN/Target -I../../../../../../../Utilities/lpm/tiny_lpm -I../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../../../../../Middlewares/ST/STM32_WPAN -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/auto -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/template -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Inc -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Src -I../../../../../../../Middlewares/ST/STM32_WPAN/ble -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/include/openthread -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/src/core -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/src/core/config -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/include -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/core/openthread_api -I../../../../../../../Middlewares/ST/STM32_WPAN/utilities -I../../../../../../../Drivers/BSP/P-NUCLEO-WB55.Nucleo -I../../../../../../../Drivers/BSP/Components/s25fl128s -I../../../../../../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc/Legacy -I../../../../../../../Middlewares/Third_Party/mbedTLS/library -I../../../../../../../Middlewares/Third_Party/mbedTLS/include -I../../../../../../../Middlewares/Third_Party/connectedhomeip/src/platform/stm32 -I../../../../../../../Middlewares/Third_Party/connectedhomeip/src/platform -Os -ffunction-sections -fdata-sections -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/Sensiron_SCD30_Driver/sensirion_i2c.o: C:/Users/olive/OneDrive/Documents/CubeMXPack/stm32wb-matter-device-over-thread-main/Drivers/Sensiron_SCD30_Driver/sensirion_i2c.c Drivers/Sensiron_SCD30_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 '-DCHIP_PLATFORM_CONFIG_INCLUDE=<CHIPPlatformConfig.h>' '-DCHIP_PROJECT_CONFIG_INCLUDE=<CHIPProjectConfig.h>' '-DMBEDTLS_CONFIG_FILE=<matter_config.h>' -DCHIP_HAVE_CONFIG_H -DUSE_HAL_DRIVER '-DOPENTHREAD_CONFIG_FILE=<openthread_api_config_matter.h>' -DCORE_CM4 -DTHREAD_WB -DDEBUG -DSTM32WB55xx -DUSE_STM32WBXX_NUCLEO -c -I../../Core/Inc -I../../Codegen/ -I../../STM32_WPAN/App -I../../STM32_WPAN/Target -I../../../../../../../Utilities/lpm/tiny_lpm -I../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../../../../../Middlewares/ST/STM32_WPAN -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/auto -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/template -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Inc -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Src -I../../../../../../../Middlewares/ST/STM32_WPAN/ble -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/include/openthread -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/src/core -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/src/core/config -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/include -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/core/openthread_api -I../../../../../../../Middlewares/ST/STM32_WPAN/utilities -I../../../../../../../Drivers/BSP/P-NUCLEO-WB55.Nucleo -I../../../../../../../Drivers/BSP/Components/s25fl128s -I../../../../../../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc/Legacy -I../../../../../../../Middlewares/Third_Party/mbedTLS/library -I../../../../../../../Middlewares/Third_Party/mbedTLS/include -I../../../../../../../Middlewares/Third_Party/connectedhomeip/src/platform/stm32 -I../../../../../../../Middlewares/Third_Party/connectedhomeip/src/platform -Os -ffunction-sections -fdata-sections -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/Sensiron_SCD30_Driver/sensirion_i2c_hal.o: C:/Users/olive/OneDrive/Documents/CubeMXPack/stm32wb-matter-device-over-thread-main/Drivers/Sensiron_SCD30_Driver/sensirion_i2c_hal.c Drivers/Sensiron_SCD30_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 '-DCHIP_PLATFORM_CONFIG_INCLUDE=<CHIPPlatformConfig.h>' '-DCHIP_PROJECT_CONFIG_INCLUDE=<CHIPProjectConfig.h>' '-DMBEDTLS_CONFIG_FILE=<matter_config.h>' -DCHIP_HAVE_CONFIG_H -DUSE_HAL_DRIVER '-DOPENTHREAD_CONFIG_FILE=<openthread_api_config_matter.h>' -DCORE_CM4 -DTHREAD_WB -DDEBUG -DSTM32WB55xx -DUSE_STM32WBXX_NUCLEO -c -I../../Core/Inc -I../../Codegen/ -I../../STM32_WPAN/App -I../../STM32_WPAN/Target -I../../../../../../../Utilities/lpm/tiny_lpm -I../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../../../../../Middlewares/ST/STM32_WPAN -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl -I../../../../../../../Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/auto -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/core/template -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Inc -I../../../../../../../Middlewares/ST/STM32_WPAN/ble/svc/Src -I../../../../../../../Middlewares/ST/STM32_WPAN/ble -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/include/openthread -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/src/core -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/src/core/config -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/stack/include -I../../../../../../../Middlewares/ST/STM32_WPAN/thread/openthread/core/openthread_api -I../../../../../../../Middlewares/ST/STM32_WPAN/utilities -I../../../../../../../Drivers/BSP/P-NUCLEO-WB55.Nucleo -I../../../../../../../Drivers/BSP/Components/s25fl128s -I../../../../../../../Drivers/CMSIS/Device/ST/STM32WBxx/Include -I../../../../../../../Drivers/CMSIS/Include -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc -I../../../../../../../Drivers/STM32WBxx_HAL_Driver/Inc/Legacy -I../../../../../../../Middlewares/Third_Party/mbedTLS/library -I../../../../../../../Middlewares/Third_Party/mbedTLS/include -I../../../../../../../Middlewares/Third_Party/connectedhomeip/src/platform/stm32 -I../../../../../../../Middlewares/Third_Party/connectedhomeip/src/platform -Os -ffunction-sections -fdata-sections -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Drivers-2f-Sensiron_SCD30_Driver

clean-Drivers-2f-Sensiron_SCD30_Driver:
	-$(RM) ./Drivers/Sensiron_SCD30_Driver/scd30_i2c.cyclo ./Drivers/Sensiron_SCD30_Driver/scd30_i2c.d ./Drivers/Sensiron_SCD30_Driver/scd30_i2c.o ./Drivers/Sensiron_SCD30_Driver/scd30_i2c.su ./Drivers/Sensiron_SCD30_Driver/sensirion_common.cyclo ./Drivers/Sensiron_SCD30_Driver/sensirion_common.d ./Drivers/Sensiron_SCD30_Driver/sensirion_common.o ./Drivers/Sensiron_SCD30_Driver/sensirion_common.su ./Drivers/Sensiron_SCD30_Driver/sensirion_i2c.cyclo ./Drivers/Sensiron_SCD30_Driver/sensirion_i2c.d ./Drivers/Sensiron_SCD30_Driver/sensirion_i2c.o ./Drivers/Sensiron_SCD30_Driver/sensirion_i2c.su ./Drivers/Sensiron_SCD30_Driver/sensirion_i2c_hal.cyclo ./Drivers/Sensiron_SCD30_Driver/sensirion_i2c_hal.d ./Drivers/Sensiron_SCD30_Driver/sensirion_i2c_hal.o ./Drivers/Sensiron_SCD30_Driver/sensirion_i2c_hal.su

.PHONY: clean-Drivers-2f-Sensiron_SCD30_Driver

